services:
  shairport-sync:
    container_name: shairport-sync
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    network_mode: host
    privileged: true
    extra_hosts:
      - "${DOCKER_LOCALHOST}:host-gateway"
    environment:
      - AIRPLAY_NAME=${AIRPLAY_NAME}
      - ENABLE_MQTT=${ENABLE_MQTT}
      - MQTT_HOSTNAME=${MQTT_HOSTNAME}
    devices:
      - "/dev/snd" # ALSA device, omit if using PulseAudio
    cap_add:
      - SYS_NICE # Found in the docs
    logging:
      options:
        max-size: "200k"
        max-file: "10"
