services:

  shairport-sync:
    container_name: shairport-sync
    image: mikebrady/shairport-sync:${SHAIRPORT_SYNC_TAG}
    labels:
      - wud.tag.include=${WUD_SEMVAR_INCLUDE_LABEL}
      - wud.link.template=https://github.com/mikebrady/shairport-sync/releases/tag/$${major}.$${minor}.$${patch}
    restart: unless-stopped
#    healthcheck:
#      # FIXME: need to import .env to actual host environment in order for this to be dynamic!
#      #      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://10.0.1.131:8777/ || exit 1"]
#      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider \"http://${DOCKER_LOCALHOST}:${ZIGBEE2MQTT_EXTERNAL_PORT}/\" || exit 1" ]
#      interval: 30s
#      timeout: 60s
#      retries: 5
#      start_period: 80s
    network_mode: host
    privileged: true
    extra_hosts:
      - "${DOCKER_LOCALHOST}:host-gateway"
    # environment:
    #  S6_KEEP_ENV: 1 # Allow S6 to pass environment variables from compose file
    #  PULSE_SERVER: unix:/tmp/pulseaudio.socket # Path for PulseAudio socket
    #  PULSE_COOKIE: /tmp/pulseaudio.cookie # Path for PulseAudio cookie
    #  XDG_RUNTIME_DIR: /tmp # Path for pipewire
    devices:
      - "/dev/snd" # ALSA device, omit if using PulseAudio
    cap_add:
      - SYS_NICE # Found in the docs
    volumes:
      - ./shairport_sync/shairport-sync.conf:/etc/shairport-sync.conf # Customised Shairport Sync configuration file.
    #   - /run/user/1000/pulse/native:/tmp/pulseaudio.socket # PulseAudio socket when using that backend
    #   - /run/user/1000/pipewire-0:/tmp/pipewire-0 # Pipewire socket when using pipewire
    # command: -o pw # You can specify the desired output with command:
    # TODO: make the name into an env var?
#    command: '-v --statistics -a Boombox -- hw:3 -c PCM'
    logging:
      options:
        max-size: "200k"
        max-file: "10"
